workflows:
  version: 2
  test:
    jobs:
      - test-2.7
      - test-3.5
      - test-3.6
      - test-latest
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    environment:
      PYTHON_VERSION=3.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Write Python version to file
          command: |
            echo $PYTHON_VERSION > /tmp/PYTHON_VERSION
            cat /tmp/PYTHON_VERSION
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "/tmp/PYTHON_VERSION" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv -p /usr/bin/python2.7 venv
            . venv/bin/activate
            pip install -e .[dev]
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "/tmp/PYTHON_VERSION" }}

      - run:
          name: Run test suite
          command: |
            . venv/bin/activate
            nosetests .
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
    environment:
      PYTHON_VERSION=3.5
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7
    environment:
      PYTHON_VERSION=2.7
  test-latest:
    <<: *test-template
    docker:
      - image: circleci/python:latest
    environment:
      PYTHON_VERSION=latest
